# .project metadata for Harbor
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "harbor"
name: "Harbor"
description: "An open source trusted cloud native registry project that stores, signs, and scans content"
type: "project"
project_lead: "reasonerjt" # TODO: AUTO-DETECTED — please verify
slack_channels: # TODO: AUTO-DETECTED — please verify the channel(s) below
  - name: "#harbor"
    link: "https://cloud-native.slack.com/messages/harbor/"
    primary: true
  - name: "#harbor-dev"
  - name: "#harbor-cli"

maturity_log:
  - phase: "graduated"
    date: "2018-07-31T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/311" # TODO: AUTO-DETECTED — please verify

repositories: # TODO: AUTO-DETECTED primary — please verify
  - url: "https://github.com/goharbor/harbor"
    primary: true
    # tags: [core, sig-apps] # Optional

website: "https://goharbor.io/"

artwork: "https://landscape.cncf.io/logos/harbor.svg"

adopters:
  path: "https://github.com/goharbor/harbor/blob/main/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "goharbor/harbor"

social:
  twitter: "https://twitter.com/project_harbor"

security:
  policy:
    path: "https://github.com/goharbor/harbor/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/goharbor/harbor/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/goharbor/harbor/blob/main/CONTRIBUTING.md"
  code_of_conduct:
    path: "https://github.com/cncf/foundation/blob/main/code-of-conduct.md"

legal:
  license:
    path: "https://github.com/goharbor/harbor/blob/main/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/goharbor/harbor/blob/main/README.md"

landscape:
  category: "Provisioning"
  subcategory: "Container Registry"

# CLOMonitor Score: 88/100
# Documentation: 94 | License: 100 | Best Practices: 74 | Security: 68
